version: '2'

services:
  mongo:
    image: mongo
    volumes:
    - ./chat/data/db:/data/db
    - ./chat/data/dump:/dump
    tty: true
    command:
    - mongod
    - --smallfiles
    - --oplogSize
    - '128'

  rocketchat:
    image: rocketchat/rocket.chat:latest
    links:
      - mongo
    environment:
      MONGO_URL: 'mongodb://mongo:27017/rocketchat'
      PORT: '3000'
      ROOT_URL: 'http://localhost:3000'
    volumes:
      - ./chat/uploads:/app/uploads
    ports:
      - '3000:3000'

  hubot-announcement:
    image: diegodorgam/hubot-rocketchat-announcement:latest
    links:
      - rocketchat
    environment:
      ROCKETCHAT_URL: 'http://rocketchat:3000'
      HUBOT_ADAPTER: rocketchat
      HUBOT_NAME: 'CatBot'
      HUBOT_DESCRIPTION: 'Creates announcements to all users in Rocket.Chat'
      ROCKETCHAT_ROOM: GENERAL
      RESPOND_TO_DM: 'true'
      RESPOND_TO_LIVECHAT: 'true'
      ROCKETCHAT_USER: catbot
      ROCKETCHAT_PASSWORD: 'catbotpass'
      ROCKETCHAT_AUTH: password
      HUBOT_LOG_LEVEL: debug
